{% set name = "crccheck" %}
{% set version = "1.1.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/crccheck-{{ version }}.tar.gz
  sha256: 14494eafba85de3ca002fc52ea4a64d698cdddfa9144429730e755e7c1430956

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 0

requirements:
  host:
    - python >=3.6
    - pip
  run:
    - python >=3.6

test:
  imports:
    - crccheck
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://sourceforge.net/projects/crccheck/
  summary: Calculation library for CRCs and checksums
  doc_url: https://pythonhosted.org/crccheck/
  license: GPL-3.0-or-later
  license_file: LICENSE

extra:
  recipe-maintainers:
    - jan-janssen
